version: "3.1"

services: 
    #Node.js server
    node-backend-server:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/backend
        ports: 
            - "3000:3000"
        links: 
            - mongo
        volumes: 
            - ./:/usr/src/backend

    #mongodb
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"